import { motion } from 'framer-motion'
import { Sparkles } from 'lucide-react'
import { useCalendarEvents } from '@/hooks/use-calendar'
import { useEmails } from '@/hooks/use-emails'
import { useNotes } from '@/hooks/use-notes'

export function SummaryCard() {
  const { data: events } = useCalendarEvents()
  const { data: emails } = useEmails()
  const { data: notes } = useNotes()

  const eventCount = events?.length ?? 0
  const unreadCount = emails?.filter((e) => !e.is_read).length ?? 0
  const noteCount = notes?.length ?? 0

  return (
    <motion.div
      className="bg-gradient-to-br from-accent/[0.04] to-transparent rounded-2xl border border-accent/10 shadow-sm p-6"
      whileHover={{ y: -1 }}
      transition={{ type: 'spring', stiffness: 300, damping: 25 }}
    >
      <div className="flex items-center gap-2.5 mb-3">
        <motion.div
          animate={{ rotate: [0, 5, -5, 0] }}
          transition={{ duration: 2, repeat: Infinity, repeatDelay: 8, ease: 'easeInOut' }}
        >
          <Sparkles className="w-4.5 h-4.5 text-accent" strokeWidth={1.5} />
        </motion.div>
        <h2 className="text-[15px] font-semibold tracking-tight">Today's Overview</h2>
      </div>
      <p className="text-[13px] text-foreground/80 leading-relaxed">
        {eventCount > 0
          ? `You have ${eventCount} event${eventCount > 1 ? 's' : ''} today`
          : 'No events scheduled'}.
        {unreadCount > 0 ? ` ${unreadCount} unread email${unreadCount > 1 ? 's' : ''}` : ' All emails read'}.
        {noteCount > 0 ? ` ${noteCount} note${noteCount > 1 ? 's' : ''} in your workspace.` : ''}
      </p>
      <div className="mt-3 flex items-center gap-1.5">
        <motion.div
          className="w-1 h-1 rounded-full bg-accent/40"
          animate={{ opacity: [0.4, 1, 0.4] }}
          transition={{ duration: 2, repeat: Infinity }}
        />
        <span className="text-[11px] text-muted-foreground">Generated by Lumio</span>
      </div>
    </motion.div>
  )
}
