# Generated by Django 5.2.16 on 2026-07-31 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
