# Generated by Django 5.2.16 on 2026-07-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
